### ISSUE TITLE
Stuck at step 3

### ISSUE THREAD

**Issue by marlouis** [lins05/mn3_anki_fix#2]
Dear, Lins05. 

Thank you very much for this script. I'm stuck at step 3 : 

3. Run the script to fix the exported apkg file before importing them to anki.
./fix_mn_anki_exports.py fix /path/to/apkg

I managed to install and run python but I don't know the process to run the script and/or indicate the correct path to Apkg. 

Here is what I did : 

1. Installed Python, when I run $ python3
I got : 
```
Python 3.10.0 (v3.10.0:b494f5935c, Oct  4 2021, 14:59:20) [Clang 12.0.5 (clang-1205.0.22.11)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

2. Exported my flashcards from MN to this path : 
/Users/josephdupont/Desktop/Droit public.apkg

3. So now I'm stuck. Here is what I get when I run the script ./fix_mn_anki_exports.py fix /path/to/apkg (after running python3 in terminal) : 
```
>>> ./fix_mn_anki_exports.py fix /Users/josephdupont/Desktop/Droit public.apkg
  File "<stdin>", line 1
    ./fix_mn_anki_exports.py fix /Users/josephdupont/Desktop/Droit public.apkg
    ^
SyntaxError: invalid syntax
>>> 
```

May I ask you to please help me (and save my exams at the same time ?..)

Thank you very much for your hard work fixing MN issues.
Best regards, 
Joseph

**Comment by lins05** [comment]
Hey, try this:

```bash
python3 ./fix_mn_anki_exports.py fix "/Users/josephdupont/Desktop/Droit public.apkg"
```

**Comment by marlouis** [comment]
Hi, thank you for your kind response. 

Here is what I get : 

```
josephs-MacBook-Pro-4:~ josephdupont$ python3
Python 3.10.0 (v3.10.0:b494f5935c, Oct  4 2021, 14:59:20) [Clang 12.0.5 (clang-1205.0.22.11)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> python3 ./fix_mn_anki_exports.py fix "/Users/josephdupont/Desktop/Droit public.apkg"
  File "<stdin>", line 1
    python3 ./fix_mn_anki_exports.py fix "/Users/josephdupont/Desktop/Droit public.apkg"
             ^
SyntaxError: invalid syntax
>>> 
```

**Comment by lins05** [comment]
You should not run the command I gave you in the python3 shell. Do this:

```
josephs-MacBook-Pro-4:~ josephdupont$ python3 ./fix_mn_anki_exports.py fix "/Users/josephdupont/Desktop/Droit public.apkg"

```

**Comment by marlouis** [comment]
Thank you Lins05 for your answer. Running the command in Terminal gave me this :

```
Last login: Mon Oct 18 12:18:29 on ttys000
You have new mail.

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
dhcp-176-155:~ josephdupont$ python3 ./fix_mn_anki_exports.py fix "/Users/josephdupont/Desktop/Droit public.apkg"
/Library/Frameworks/Python.framework/Versions/3.10/bin/python3: can't open file '/Users/josephdupont/./fix_mn_anki_exports.py': [Errno 2] No such file or directory
dhcp-176-155:~ josephdupont$ 
```

Edit : 

I moved the fix_mn_anki_exports.py file to /Users/josephdupont 
Now I have this : 

```
dhcp-176-155:~ josephdupont$ python3 ./fix_mn_anki_exports.py fix "/Users/josephdupont/Desktop/Droit public.apkg"
Traceback (most recent call last):
  File "/Users/josephdupont/./fix_mn_anki_exports.py", line 27, in <module>
    import click
ModuleNotFoundError: No module named 'click'
dhcp-176-155:~ josephdupont$ 
```

**Comment by lins05** [comment]
You should run the command I give you in the folder of this project, e..g

```
cd /path/to/mn3_anki_fix
<now run the command I gave you>
```

**Comment by marlouis** [comment]
Thanks again. Here is what I got : 

```
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
dhcp-176-155:~ josephdupont$ cd /Users/josephdupont/Desktop/mn3_anki_fix-master
dhcp-176-155:mn3_anki_fix-master josephdupont$ python3 ./fix_mn_anki_exports.py fix "/Users/josephdupont/Desktop/Droit public.apkg"
Traceback (most recent call last):
  File "/Users/josephdupont/Desktop/mn3_anki_fix-master/./fix_mn_anki_exports.py", line 27, in <module>
    import click
ModuleNotFoundError: No module named 'click'
dhcp-176-155:mn3_anki_fix-master josephdupont$ 
```

**Comment by lins05** [comment]
Did you run the pip3 command as mentioned in the readme file?

**Comment by marlouis** [comment]
> Did you run the pip3 command as mentioned in the readme file?

Ok yes, sorry. See : 

`Successfully installed pip-21.3 wheel-0.37.0`

`Successfully installed click-8.0.3`

`Successfully installed six-1.16.0 w3lib-1.22.0`

`Successfully installed strsimpy-0.2.1`

`Successfully installed cached-property-1.5.2 frozendict-2.0.6 genanki-0.11.0 pystache-0.5.4 pyyaml-6.0`


Then running your command gave me :

```

dhcp-176-155:~ josephdupont$ cd /Users/josephdupont/Desktop/mn3_anki_fix-master
dhcp-176-155:mn3_anki_fix-master josephdupont$ python3 ./fix_mn_anki_exports.py fix "/Users/josephdupont/Desktop/Droit public.apkg"
[10/19/2021 09:50:34][fix_mn_anki_exports]: files: ['18', '9', '0', '11', '7', '16', '6', '17', '1', '10', '19', '8', 'collection.anki2', '4', '15', '3', '12', '2', '13', '5', '14', 'media']
[10/19/2021 09:50:34][fix_mn_anki_exports]: Extracted collection.anki2 to /tmp/mn-anki-exports-fix/tmp2ma3cm05
Traceback (most recent call last):
  File "/Users/josephdupont/Desktop/mn3_anki_fix-master/./fix_mn_anki_exports.py", line 346, in <module>
    main(obj={})
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/josephdupont/Desktop/mn3_anki_fix-master/./fix_mn_anki_exports.py", line 304, in fix
    _fix_path(path)
  File "/Users/josephdupont/Desktop/mn3_anki_fix-master/./fix_mn_anki_exports.py", line 317, in _fix_path
    _fix_dbfile(dbfile)
  File "/Users/josephdupont/Desktop/mn3_anki_fix-master/./fix_mn_anki_exports.py", line 56, in _fix_dbfile
    return _fix_db(db)
  File "/Users/josephdupont/Desktop/mn3_anki_fix-master/./fix_mn_anki_exports.py", line 272, in _fix_db
    cloze_model, non_cloze_model = _model_from_db(db)
  File "/Users/josephdupont/Desktop/mn3_anki_fix-master/./fix_mn_anki_exports.py", line 92, in _model_from_db
    cloze_model = genanki.Model(
TypeError: Model.__init__() got an unexpected keyword argument 'type'
dhcp-176-155:mn3_anki_fix-master josephdupont$ 
```

**Comment by marlouis** [comment]
Dear lins05, 

I've managed to finally get the script to work. Now I'm facing the following problem : 

When exporting from MN3 with "Mask the Emphasis in text" option off : 

![2](https://user-images.githubusercontent.com/62121383/138280262-88991b2e-47c7-45e3-bb1c-f6e9dcc7b7ed.png)

Everything works fine : 

<img width="951" alt="CleanShot 2021-10-21 at 14 41 14@2x" src="https://user-images.githubusercontent.com/62121383/138279322-f275573a-066a-4b96-978c-c113948a43fb.png">

But then the cloze deletion are shown with underline.
<img width="663" alt="CleanShot 2021-10-21 at 14 42 00@2x" src="https://user-images.githubusercontent.com/62121383/138279541-e92f1985-f187-42f2-9423-cc933d704b88.png">

So I tried exporting from MN3 with "Mask the Emphasis in text" option on : 
<img width="1920" alt="With  Mask the Emphasis in text" src="https://user-images.githubusercontent.com/62121383/138279758-f33ef052-7b28-4c7d-9e53-ed767708a776.png">

But then I got this message in terminal when running your command : 

```
dhcp-181-29:mn3_anki_fix-master josephdupont$ ./fix_mn_anki_exports.py fix "/Users/josephdupont/Desktop/With.apkg"
[10/21/2021 14:44:17][fix_mn_anki_exports]: files: ['collection.anki2', 'media']
[10/21/2021 14:44:17][fix_mn_anki_exports]: Extracted collection.anki2 to /tmp/mn-anki-exports-fix/tmplljjj4v_
[10/21/2021 14:44:17][fix_mn_anki_exports]: Loaded the model
[10/21/2021 14:44:17][fix_mn_anki_exports]: Loaded 48 notes
[10/21/2021 14:44:17][fix_mn_anki_exports]: Fixed all 48 notes
[10/21/2021 14:44:17][fix_mn_anki_exports]: Loaded deck info: deck name = 20184556082557, id = Droit public - Chapitre 5 : les autorités indépendantes
[10/21/2021 14:44:17][fix_mn_anki_exports]: Generating output file /tmp/output.apkg
Traceback (most recent call last):
  File "/Users/josephdupont/Desktop/mn3_anki_fix-master/./fix_mn_anki_exports.py", line 346, in <module>
    main(obj={})
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/josephdupont/Desktop/mn3_anki_fix-master/./fix_mn_anki_exports.py", line 304, in fix
    _fix_path(path)
  File "/Users/josephdupont/Desktop/mn3_anki_fix-master/./fix_mn_anki_exports.py", line 317, in _fix_path
    _fix_dbfile(dbfile)
  File "/Users/josephdupont/Desktop/mn3_anki_fix-master/./fix_mn_anki_exports.py", line 56, in _fix_dbfile
    return _fix_db(db)
  File "/Users/josephdupont/Desktop/mn3_anki_fix-master/./fix_mn_anki_exports.py", line 284, in _fix_db
    genanki.Package(deck).write_to_file(OUTPUT_FILE)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/genanki/package.py", line 29, in write_to_file
    self.write_to_db(cursor, now_ts)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/genanki/package.py", line 49, in write_to_db
    deck.write_to_db(cursor, now_ts)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/genanki/deck.py", line 67, in write_to_db
    note.write_to_db(cursor, now_ts, self.deck_id)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/genanki/note.py", line 69, in write_to_db
    card.write_to_db(cursor, now_ts, deck_id, note_id)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/genanki/card.py", line 9, in write_to_db
    cursor.execute('INSERT INTO cards VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);', (
sqlite3.IntegrityError: UNIQUE constraint failed: cards.id
dhcp-181-29:mn3_anki_fix-master josephdupont$ 
```

Did I do something wrong ? 

Regards, 
Joseph

**Comment by lins05** [comment]
This tool was written several years ago, and most likely the format of the apkg file exported by MN has been changed so far.  I'm sorry but I don't want to invest into this anymore because I myself isn't using it.
